if(LINGMO_ENABLE_SANITIZERS)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        add_compile_options(-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address -fsanitize=undefined)
    elseif(MSVC)
        message(STATUS "MSVC: AddressSanitizer enabled via /fsanitize=address")
        add_compile_options(/fsanitize=address)
        add_link_options(/fsanitize=address)
    endif()
endif()
